spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fleetops}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:fleetops}
    password: ${DB_PASSWORD:fleetops}

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  data:
    web:
      pageable:
        default-page-size: 15
        max-page-size: 100

  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.boot.security.autoconfigure: WARN
    org.hibernate.SQL: ERROR
    rs.tiacgroup.fleetopsgateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger - %msg%n"

provider:
  free:
    base-url: http://localhost:8081/free-third-party
    connect-timeout: 2000
    read-timeout: 5000
  premium:
    base-url: http://localhost:8081/premium-third-party
    connect-timeout: 2000
    read-timeout: 2000

cors:
  allowed-origins: http://localhost:4200

resilience4j:
  circuitbreaker:
    instances:
      freeProvider:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
      premiumProvider:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, circuitbreakers, circuitbreakerevents
  endpoint:
    health:
      show-details: always